// src/consts.ts

export const typeCheckingOperators = [
  "IS_BOOL",
  "IS_NULL",
  "IS_ARRAY",
  "IS_NUMBER",
  "IS_OBJECT",
  "IS_STRING",
  "IS_INTEGER",
  "IS_DEFINED",
  "IS_PRIMITIVE",
  "IS_FINITE_NUMBER",
];

export const allowedOperators = [
  "=",
  "!=",
  ">",
  ">=",
  "<",
  "<=",
  "IN",
  "NOT IN",
  "LIKE",
  "IS_BOOL",
  "IS_NULL",
  "IS_ARRAY",
  "IS_NUMBER",
  "IS_OBJECT",
  "IS_STRING",
  "IS_INTEGER",
  "IS_DEFINED",
  "IS_PRIMITIVE",
  "IS_FINITE_NUMBER",
  "IS_NOT_BOOL",
  "IS_NOT_NULL",
  "IS_NOT_ARRAY",
  "IS_NOT_NUMBER",
  "IS_NOT_OBJECT",
  "IS_NOT_STRING",
  "IS_NOT_INTEGER",
  "IS_NOT_DEFINED",
  "IS_NOT_PRIMITIVE",
  "IS_NOT_FINITE_NUMBER",
];
